version: '3.1'
services:
  api:
    build: ./api
    command: python api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/api
    ports:
      - '8000:8000'
    depends_on:
      - mysql-db
  
  mysql-db:
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: fittin_password
      MYSQL_DATABASE: fittin
    ports:
      - 3307:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  
volumes:
  mysql-data: