# Generated by Django 4.0.6 on 2022-07-21 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=40)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('barcode', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('available', models.BooleanField()),
                ('params', models.JSONField()),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('percent', models.IntegerField()),
                ('vat', models.IntegerField()),
                ('model', models.CharField(max_length=120)),
                ('vendor_code', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('price_begin', models.FloatField()),
                ('category', models.ManyToManyField(related_name='products', to='products.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='OfferPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.CharField(max_length=300)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='products.offer')),
            ],
            options={
                'db_table': 'offer_picture',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.product'),
        ),
    ]
