# Generated by Django 4.0.6 on 2022-07-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_begin',
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='price_begin',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
