# Generated by Django 4.0.6 on 2022-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_offer_price_remove_offer_price_begin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerpicture',
            name='picture_url',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
