# Generated by Django 4.0.6 on 2022-07-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_offerpicture_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerpicture',
            name='picture_url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
